server:
  port: 9966
spring:
  application:
    name: edu-config-boot
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/rangang/lagou-config.git #gitee项目地址
          username: 13452334233@163.com
          password: ran@0704
          search-paths:
            - lagou-config
          default-label: master
          clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: http://172.16.167.20:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
