server:
  port: 9966
spring:
  application:
    name: edu-config-boot
  cloud:
    config:
      server:
        git:
          uri: xx #gitee项目地址
          username: xx
          password: xx
          search-paths:
            - lagou-config
          default-label: master
          clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
