server:
  port: 8009
spring:
  application:
    name: edu-file-boot
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

aliyun:
  oss:
    endpoint: xx
    accessKeyId: xx
    secret: xx
    bucket: xx