server:
  port: 8005
spring:
  application:
    name: edu-comment-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu_comment?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Ran@123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
